
apiVersion: skaffold/v1beta15
kind: Config
build:
  tagPolicy:
    sha256: {}
  # defines where to find the code at build time and where to push the resulting image
  artifacts:
    - image: emailservice
      context: src/emailservice
    - image: recommendationservice
      context: src/recommendationservice
    - image: shippingservice
      context: src/shippingservice
    - image: checkoutservice
      context: src/checkoutservice
    - image: paymentservice
      context: src/paymentservice
    - image: currencyservice
      context: src/currencyservice
    - image: cartservice
      context: src/cartservice
    - image: adservice
      context: src/adservice
    - image: productcatalogservicephp
      context: src/productcatalogservicephp
    - image: gateway
      context: src/gateway
    - image: frontend
      context: src/frontend
# defines the Kubernetes manifests to deploy on each run
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/**.yaml
profiles:
# use the cloudbuild profile to build images using Google Cloud Build
- name: cloudbuild
  build:
    googleCloudBuild: {}
