<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto

namespace Hipstershop;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>hipstershop.Ad</code>
 */
class Ad extends \Google\Protobuf\Internal\Message
{
    /**
     * url to redirect to when an ad is clicked.
     *
     * Generated from protobuf field <code>string redirect_url = 1;</code>
     */
    private $redirect_url = '';
    /**
     * short advertisement text to display.
     *
     * Generated from protobuf field <code>string text = 2;</code>
     */
    private $text = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $redirect_url
     *           url to redirect to when an ad is clicked.
     *     @type string $text
     *           short advertisement text to display.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Demo::initOnce();
        parent::__construct($data);
    }

    /**
     * url to redirect to when an ad is clicked.
     *
     * Generated from protobuf field <code>string redirect_url = 1;</code>
     * @return string
     */
    public function getRedirectUrl()
    {
        return $this->redirect_url;
    }

    /**
     * url to redirect to when an ad is clicked.
     *
     * Generated from protobuf field <code>string redirect_url = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRedirectUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->redirect_url = $var;

        return $this;
    }

    /**
     * short advertisement text to display.
     *
     * Generated from protobuf field <code>string text = 2;</code>
     * @return string
     */
    public function getText()
    {
        return $this->text;
    }

    /**
     * short advertisement text to display.
     *
     * Generated from protobuf field <code>string text = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setText($var)
    {
        GPBUtil::checkString($var, True);
        $this->text = $var;

        return $this;
    }

}

