<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto

namespace Hipstershop;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>hipstershop.AdResponse</code>
 */
class AdResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .hipstershop.Ad ads = 1;</code>
     */
    private $ads;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Hipstershop\Ad[]|\Google\Protobuf\Internal\RepeatedField $ads
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Demo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .hipstershop.Ad ads = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAds()
    {
        return $this->ads;
    }

    /**
     * Generated from protobuf field <code>repeated .hipstershop.Ad ads = 1;</code>
     * @param \Hipstershop\Ad[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Hipstershop\Ad::class);
        $this->ads = $arr;

        return $this;
    }

}

