<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto

namespace Hipstershop;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>hipstershop.ChargeRequest</code>
 */
class ChargeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.hipstershop.Money amount = 1;</code>
     */
    private $amount = null;
    /**
     * Generated from protobuf field <code>.hipstershop.CreditCardInfo credit_card = 2;</code>
     */
    private $credit_card = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Hipstershop\Money $amount
     *     @type \Hipstershop\CreditCardInfo $credit_card
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Demo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.hipstershop.Money amount = 1;</code>
     * @return \Hipstershop\Money
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>.hipstershop.Money amount = 1;</code>
     * @param \Hipstershop\Money $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkMessage($var, \Hipstershop\Money::class);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.hipstershop.CreditCardInfo credit_card = 2;</code>
     * @return \Hipstershop\CreditCardInfo
     */
    public function getCreditCard()
    {
        return $this->credit_card;
    }

    /**
     * Generated from protobuf field <code>.hipstershop.CreditCardInfo credit_card = 2;</code>
     * @param \Hipstershop\CreditCardInfo $var
     * @return $this
     */
    public function setCreditCard($var)
    {
        GPBUtil::checkMessage($var, \Hipstershop\CreditCardInfo::class);
        $this->credit_card = $var;

        return $this;
    }

}

