<?php
# Generated by the protocol buffer compiler (spiral/php-grpc). DO NOT EDIT!
# source: demo.proto

namespace Hipstershop;

use Spiral\GRPC;

interface CheckoutServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "hipstershop.CheckoutService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param PlaceOrderRequest $in
    * @return PlaceOrderResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function PlaceOrder(GRPC\ContextInterface $ctx, PlaceOrderRequest $in): PlaceOrderResponse;
}
