<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto

namespace Hipstershop;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>hipstershop.GetQuoteResponse</code>
 */
class GetQuoteResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.hipstershop.Money cost_usd = 1;</code>
     */
    private $cost_usd = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Hipstershop\Money $cost_usd
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Demo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.hipstershop.Money cost_usd = 1;</code>
     * @return \Hipstershop\Money
     */
    public function getCostUsd()
    {
        return $this->cost_usd;
    }

    /**
     * Generated from protobuf field <code>.hipstershop.Money cost_usd = 1;</code>
     * @param \Hipstershop\Money $var
     * @return $this
     */
    public function setCostUsd($var)
    {
        GPBUtil::checkMessage($var, \Hipstershop\Money::class);
        $this->cost_usd = $var;

        return $this;
    }

}

