<?php
# Generated by the protocol buffer compiler (spiral/php-grpc). DO NOT EDIT!
# source: demo.proto

namespace Hipstershop;

use Spiral\GRPC;

interface RecommendationServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "hipstershop.RecommendationService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param ListRecommendationsRequest $in
    * @return ListRecommendationsResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function ListRecommendations(GRPC\ContextInterface $ctx, ListRecommendationsRequest $in): ListRecommendationsResponse;
}
