<?php
# Generated by the protocol buffer compiler (spiral/php-grpc). DO NOT EDIT!
# source: demo.proto

namespace Hipstershop;

use Spiral\GRPC;

interface AdServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "hipstershop.AdService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param AdRequest $in
    * @return AdResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function GetAds(GRPC\ContextInterface $ctx, AdRequest $in): AdResponse;
}
