<?php
# Generated by the protocol buffer compiler (spiral/php-grpc). DO NOT EDIT!
# source: demo.proto

namespace Hipstershop;

use Spiral\GRPC;

interface CartServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "hipstershop.CartService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param AddItemRequest $in
    * @return Empty
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function AddItem(GRPC\ContextInterface $ctx, AddItemRequest $in): Empty;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param GetCartRequest $in
    * @return Cart
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function GetCart(GRPC\ContextInterface $ctx, GetCartRequest $in): Cart;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param EmptyCartRequest $in
    * @return Empty
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function EmptyCart(GRPC\ContextInterface $ctx, EmptyCartRequest $in): Empty;
}
