<?php
# Generated by the protocol buffer compiler (spiral/php-grpc). DO NOT EDIT!
# source: demo.proto

namespace Hipstershop;

use Spiral\GRPC;

interface CurrencyServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "hipstershop.CurrencyService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param Empty $in
    * @return GetSupportedCurrenciesResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function GetSupportedCurrencies(GRPC\ContextInterface $ctx, Empty $in): GetSupportedCurrenciesResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param CurrencyConversionRequest $in
    * @return Money
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Convert(GRPC\ContextInterface $ctx, CurrencyConversionRequest $in): Money;
}
