<?php
# Generated by the protocol buffer compiler (spiral/php-grpc). DO NOT EDIT!
# source: demo.proto

namespace Hipstershop;

use Spiral\GRPC;

interface EmailServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "hipstershop.EmailService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param SendOrderConfirmationRequest $in
    * @return Empty
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function SendOrderConfirmation(GRPC\ContextInterface $ctx, SendOrderConfirmationRequest $in): Empty;
}
