<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto

namespace Hipstershop;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>hipstershop.GetQuoteRequest</code>
 */
class GetQuoteRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.hipstershop.Address address = 1;</code>
     */
    private $address = null;
    /**
     * Generated from protobuf field <code>repeated .hipstershop.CartItem items = 2;</code>
     */
    private $items;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Hipstershop\Address $address
     *     @type \Hipstershop\CartItem[]|\Google\Protobuf\Internal\RepeatedField $items
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Demo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.hipstershop.Address address = 1;</code>
     * @return \Hipstershop\Address
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>.hipstershop.Address address = 1;</code>
     * @param \Hipstershop\Address $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkMessage($var, \Hipstershop\Address::class);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .hipstershop.CartItem items = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * Generated from protobuf field <code>repeated .hipstershop.CartItem items = 2;</code>
     * @param \Hipstershop\CartItem[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Hipstershop\CartItem::class);
        $this->items = $arr;

        return $this;
    }

}

