<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto

namespace Hipstershop;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>hipstershop.GetSupportedCurrenciesResponse</code>
 */
class GetSupportedCurrenciesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The 3-letter currency code defined in ISO 4217.
     *
     * Generated from protobuf field <code>repeated string currency_codes = 1;</code>
     */
    private $currency_codes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $currency_codes
     *           The 3-letter currency code defined in ISO 4217.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Demo::initOnce();
        parent::__construct($data);
    }

    /**
     * The 3-letter currency code defined in ISO 4217.
     *
     * Generated from protobuf field <code>repeated string currency_codes = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCurrencyCodes()
    {
        return $this->currency_codes;
    }

    /**
     * The 3-letter currency code defined in ISO 4217.
     *
     * Generated from protobuf field <code>repeated string currency_codes = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCurrencyCodes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->currency_codes = $arr;

        return $this;
    }

}

