<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto

namespace Hipstershop;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>hipstershop.OrderResult</code>
 */
class OrderResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string order_id = 1;</code>
     */
    private $order_id = '';
    /**
     * Generated from protobuf field <code>string shipping_tracking_id = 2;</code>
     */
    private $shipping_tracking_id = '';
    /**
     * Generated from protobuf field <code>.hipstershop.Money shipping_cost = 3;</code>
     */
    private $shipping_cost = null;
    /**
     * Generated from protobuf field <code>.hipstershop.Address shipping_address = 4;</code>
     */
    private $shipping_address = null;
    /**
     * Generated from protobuf field <code>repeated .hipstershop.OrderItem items = 5;</code>
     */
    private $items;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $order_id
     *     @type string $shipping_tracking_id
     *     @type \Hipstershop\Money $shipping_cost
     *     @type \Hipstershop\Address $shipping_address
     *     @type \Hipstershop\OrderItem[]|\Google\Protobuf\Internal\RepeatedField $items
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Demo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string order_id = 1;</code>
     * @return string
     */
    public function getOrderId()
    {
        return $this->order_id;
    }

    /**
     * Generated from protobuf field <code>string order_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderId($var)
    {
        GPBUtil::checkString($var, True);
        $this->order_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string shipping_tracking_id = 2;</code>
     * @return string
     */
    public function getShippingTrackingId()
    {
        return $this->shipping_tracking_id;
    }

    /**
     * Generated from protobuf field <code>string shipping_tracking_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setShippingTrackingId($var)
    {
        GPBUtil::checkString($var, True);
        $this->shipping_tracking_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.hipstershop.Money shipping_cost = 3;</code>
     * @return \Hipstershop\Money
     */
    public function getShippingCost()
    {
        return $this->shipping_cost;
    }

    /**
     * Generated from protobuf field <code>.hipstershop.Money shipping_cost = 3;</code>
     * @param \Hipstershop\Money $var
     * @return $this
     */
    public function setShippingCost($var)
    {
        GPBUtil::checkMessage($var, \Hipstershop\Money::class);
        $this->shipping_cost = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.hipstershop.Address shipping_address = 4;</code>
     * @return \Hipstershop\Address
     */
    public function getShippingAddress()
    {
        return $this->shipping_address;
    }

    /**
     * Generated from protobuf field <code>.hipstershop.Address shipping_address = 4;</code>
     * @param \Hipstershop\Address $var
     * @return $this
     */
    public function setShippingAddress($var)
    {
        GPBUtil::checkMessage($var, \Hipstershop\Address::class);
        $this->shipping_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .hipstershop.OrderItem items = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * Generated from protobuf field <code>repeated .hipstershop.OrderItem items = 5;</code>
     * @param \Hipstershop\OrderItem[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Hipstershop\OrderItem::class);
        $this->items = $arr;

        return $this;
    }

}

