<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto

namespace Hipstershop;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>hipstershop.OrderItem</code>
 */
class OrderItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.hipstershop.CartItem item = 1;</code>
     */
    private $item = null;
    /**
     * Generated from protobuf field <code>.hipstershop.Money cost = 2;</code>
     */
    private $cost = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Hipstershop\CartItem $item
     *     @type \Hipstershop\Money $cost
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Demo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.hipstershop.CartItem item = 1;</code>
     * @return \Hipstershop\CartItem
     */
    public function getItem()
    {
        return $this->item;
    }

    /**
     * Generated from protobuf field <code>.hipstershop.CartItem item = 1;</code>
     * @param \Hipstershop\CartItem $var
     * @return $this
     */
    public function setItem($var)
    {
        GPBUtil::checkMessage($var, \Hipstershop\CartItem::class);
        $this->item = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.hipstershop.Money cost = 2;</code>
     * @return \Hipstershop\Money
     */
    public function getCost()
    {
        return $this->cost;
    }

    /**
     * Generated from protobuf field <code>.hipstershop.Money cost = 2;</code>
     * @param \Hipstershop\Money $var
     * @return $this
     */
    public function setCost($var)
    {
        GPBUtil::checkMessage($var, \Hipstershop\Money::class);
        $this->cost = $var;

        return $this;
    }

}

