<?php
# Generated by the protocol buffer compiler (spiral/php-grpc). DO NOT EDIT!
# source: demo.proto

namespace Hipstershop;

use Spiral\GRPC;

interface PaymentServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "hipstershop.PaymentService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param ChargeRequest $in
    * @return ChargeResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Charge(GRPC\ContextInterface $ctx, ChargeRequest $in): ChargeResponse;
}
