<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto

namespace Hipstershop;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>hipstershop.PlaceOrderRequest</code>
 */
class PlaceOrderRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     */
    private $user_id = '';
    /**
     * Generated from protobuf field <code>string user_currency = 2;</code>
     */
    private $user_currency = '';
    /**
     * Generated from protobuf field <code>.hipstershop.Address address = 3;</code>
     */
    private $address = null;
    /**
     * Generated from protobuf field <code>string email = 5;</code>
     */
    private $email = '';
    /**
     * Generated from protobuf field <code>.hipstershop.CreditCardInfo credit_card = 6;</code>
     */
    private $credit_card = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $user_id
     *     @type string $user_currency
     *     @type \Hipstershop\Address $address
     *     @type string $email
     *     @type \Hipstershop\CreditCardInfo $credit_card
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Demo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_currency = 2;</code>
     * @return string
     */
    public function getUserCurrency()
    {
        return $this->user_currency;
    }

    /**
     * Generated from protobuf field <code>string user_currency = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUserCurrency($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_currency = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.hipstershop.Address address = 3;</code>
     * @return \Hipstershop\Address
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>.hipstershop.Address address = 3;</code>
     * @param \Hipstershop\Address $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkMessage($var, \Hipstershop\Address::class);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string email = 5;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Generated from protobuf field <code>string email = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.hipstershop.CreditCardInfo credit_card = 6;</code>
     * @return \Hipstershop\CreditCardInfo
     */
    public function getCreditCard()
    {
        return $this->credit_card;
    }

    /**
     * Generated from protobuf field <code>.hipstershop.CreditCardInfo credit_card = 6;</code>
     * @param \Hipstershop\CreditCardInfo $var
     * @return $this
     */
    public function setCreditCard($var)
    {
        GPBUtil::checkMessage($var, \Hipstershop\CreditCardInfo::class);
        $this->credit_card = $var;

        return $this;
    }

}

