<?php
# Generated by the protocol buffer compiler (spiral/php-grpc). DO NOT EDIT!
# source: demo.proto

namespace Hipstershop;

use Spiral\GRPC;

interface ProductCatalogServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "hipstershop.ProductCatalogService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param PBEmpty $in
    * @return ListProductsResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function ListProducts(GRPC\ContextInterface $ctx, PBEmpty $in): ListProductsResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param GetProductRequest $in
    * @return Product
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function GetProduct(GRPC\ContextInterface $ctx, GetProductRequest $in): Product;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param SearchProductsRequest $in
    * @return SearchProductsResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function SearchProducts(GRPC\ContextInterface $ctx, SearchProductsRequest $in): SearchProductsResponse;
}
