<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto

namespace Hipstershop;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>hipstershop.Product</code>
 */
class Product extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    private $id = '';
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>string description = 3;</code>
     */
    private $description = '';
    /**
     * Generated from protobuf field <code>string picture = 4;</code>
     */
    private $picture = '';
    /**
     * Generated from protobuf field <code>.hipstershop.Money price_usd = 5;</code>
     */
    private $price_usd = null;
    /**
     * Categories such as "vintage" or "gardening" that can be used to look up
     * other related products.
     *
     * Generated from protobuf field <code>repeated string categories = 6;</code>
     */
    private $categories;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $name
     *     @type string $description
     *     @type string $picture
     *     @type \Hipstershop\Money $price_usd
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $categories
     *           Categories such as "vintage" or "gardening" that can be used to look up
     *           other related products.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Demo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 3;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string picture = 4;</code>
     * @return string
     */
    public function getPicture()
    {
        return $this->picture;
    }

    /**
     * Generated from protobuf field <code>string picture = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPicture($var)
    {
        GPBUtil::checkString($var, True);
        $this->picture = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.hipstershop.Money price_usd = 5;</code>
     * @return \Hipstershop\Money
     */
    public function getPriceUsd()
    {
        return $this->price_usd;
    }

    /**
     * Generated from protobuf field <code>.hipstershop.Money price_usd = 5;</code>
     * @param \Hipstershop\Money $var
     * @return $this
     */
    public function setPriceUsd($var)
    {
        GPBUtil::checkMessage($var, \Hipstershop\Money::class);
        $this->price_usd = $var;

        return $this;
    }

    /**
     * Categories such as "vintage" or "gardening" that can be used to look up
     * other related products.
     *
     * Generated from protobuf field <code>repeated string categories = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCategories()
    {
        return $this->categories;
    }

    /**
     * Categories such as "vintage" or "gardening" that can be used to look up
     * other related products.
     *
     * Generated from protobuf field <code>repeated string categories = 6;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCategories($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->categories = $arr;

        return $this;
    }

}

