<?php
# Generated by the protocol buffer compiler (spiral/php-grpc). DO NOT EDIT!
# source: demo.proto

namespace Hipstershop;

use Spiral\GRPC;

interface ShippingServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "hipstershop.ShippingService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param GetQuoteRequest $in
    * @return GetQuoteResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function GetQuote(GRPC\ContextInterface $ctx, GetQuoteRequest $in): GetQuoteResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param ShipOrderRequest $in
    * @return ShipOrderResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function ShipOrder(GRPC\ContextInterface $ctx, ShipOrderRequest $in): ShipOrderResponse;
}
