<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

namespace GPBMetadata;

class Test
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a570a0a746573742e70726f746f12077365727669636522070a05456d70" .
            "7479322f0a036d737812280a0450696e67120e2e736572766963652e456d" .
            "7074791a0e2e736572766963652e456d7074792200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

